micronaut:
  application:
    name: backend-challenge
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  endpoints:
    health:
      enabled: true
      sensitive: false
      details-visible: ANONYMOUS
      url:
        enabled: true
